### ISSUE TITLE
Chopper 7.X.X mockito not working anymore.

### ISSUE THREAD

**Issue by frederikstonge** [lejard-h/chopper#478] opened 2023-08-11 11:33 UTC
## Steps to Reproduce

We had a mock (generated with mokito) of a chopper service that was working fine, but it looks like the new version broke something because right now it gives me this exception :

```
MissingDummyValueError: Response<SearchModel>

This means Mockito was not smart enough to generate a dummy value of type
'Response<SearchModel>'. Please consider using either 'provideDummy' or 'provideDummyBuilder'
functions to give Mockito a proper dummy value.

Please note that due to implementation details Mockito sometimes needs users
to provide dummy values for some types, even if they plan to explicitly stub
 all the called methods.
```

7.X.X generated version of the file :
```dart
// Mocks generated by Mockito 5.4.2 from annotations
// in mobile_shop/test/src/presentation/features/search_results/bloc/search_result_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chopper/chopper.dart' as _i3;
import 'package:hydrated_bloc/src/hydrated_storage.dart' as _i7;
import 'package:mobile_shop/src/core/bfm/generated/mobile_facade.models.swagger.dart'
    as _i6;
import 'package:mobile_shop/src/core/bfm/generated/mobile_facade.swagger.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeType_0 extends _i1.SmartFake implements Type {
  _FakeType_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MobileFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockMobileFacade extends _i1.Mock implements _i2.MobileFacade {
  MockMobileFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChopperClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _i4.dummyValue<_i3.ChopperClient>(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.ChopperClient);
  @override
  set client(_i3.ChopperClient? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Type get definitionType => (super.noSuchMethod(
        Invocation.getter(#definitionType),
        returnValue: _FakeType_0(
          this,
          Invocation.getter(#definitionType),
        ),
      ) as Type);
  @override
  _i5.Future<_i3.Response<_i6.AuthorizationModel>>
      apiV1AuthenticationTokenPost({
    String? authenticationToken,
    String? accountId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #apiV1AuthenticationTokenPost,
              [],
              {
                #authenticationToken: authenticationToken,
                #accountId: accountId,
              },
            ),
            returnValue: _i5.Future<_i3.Response<_i6.AuthorizationModel>>.value(
                _i4.dummyValue<_i3.Response<_i6.AuthorizationModel>>(
              this,
              Invocation.method(
                #apiV1AuthenticationTokenPost,
                [],
                {
                  #authenticationToken: authenticationToken,
                  #accountId: accountId,
                },
              ),
            )),
          ) as _i5.Future<_i3.Response<_i6.AuthorizationModel>>);
  @override
  _i5.Future<_i3.Response<_i6.CredentialModel>> apiV1AuthenticationRefreshPost(
          {String? refreshToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1AuthenticationRefreshPost,
          [],
          {#refreshToken: refreshToken},
        ),
        returnValue: _i5.Future<_i3.Response<_i6.CredentialModel>>.value(
            _i4.dummyValue<_i3.Response<_i6.CredentialModel>>(
          this,
          Invocation.method(
            #apiV1AuthenticationRefreshPost,
            [],
            {#refreshToken: refreshToken},
          ),
        )),
      ) as _i5.Future<_i3.Response<_i6.CredentialModel>>);
  @override
  _i5.Future<_i3.Response<dynamic>> apiV1HealthReadinessGet() =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1HealthReadinessGet,
          [],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiV1HealthReadinessGet,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
  @override
  _i5.Future<_i3.Response<dynamic>> apiV1HealthLivenessGet() =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1HealthLivenessGet,
          [],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiV1HealthLivenessGet,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
  @override
  _i5.Future<_i3.Response<List<_i6.CategoryModel>>>
      apiV1ProductCategoriesGet() => (super.noSuchMethod(
            Invocation.method(
              #apiV1ProductCategoriesGet,
              [],
            ),
            returnValue:
                _i5.Future<_i3.Response<List<_i6.CategoryModel>>>.value(
                    _i4.dummyValue<_i3.Response<List<_i6.CategoryModel>>>(
              this,
              Invocation.method(
                #apiV1ProductCategoriesGet,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Response<List<_i6.CategoryModel>>>);
  @override
  _i5.Future<_i3.Response<_i6.SuggestionsModel>>
      apiV1ProductSearchTypeaheadQueryGet({required String? query}) =>
          (super.noSuchMethod(
            Invocation.method(
              #apiV1ProductSearchTypeaheadQueryGet,
              [],
              {#query: query},
            ),
            returnValue: _i5.Future<_i3.Response<_i6.SuggestionsModel>>.value(
                _i4.dummyValue<_i3.Response<_i6.SuggestionsModel>>(
              this,
              Invocation.method(
                #apiV1ProductSearchTypeaheadQueryGet,
                [],
                {#query: query},
              ),
            )),
          ) as _i5.Future<_i3.Response<_i6.SuggestionsModel>>);
  @override
  _i5.Future<_i3.Response<_i6.SearchModel>> apiV1ProductSearchPost(
          {required _i6.SearchRequestModel? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1ProductSearchPost,
          [],
          {#body: body},
        ),
        returnValue: _i5.Future<_i3.Response<_i6.SearchModel>>.value(
            _i4.dummyValue<_i3.Response<_i6.SearchModel>>(
          this,
          Invocation.method(
            #apiV1ProductSearchPost,
            [],
            {#body: body},
          ),
        )),
      ) as _i5.Future<_i3.Response<_i6.SearchModel>>);
  @override
  _i5.Future<_i3.Response<_i6.SearchTermHistoryModel>>
      apiV1ProductSearchHistoryTermsGet() => (super.noSuchMethod(
            Invocation.method(
              #apiV1ProductSearchHistoryTermsGet,
              [],
            ),
            returnValue:
                _i5.Future<_i3.Response<_i6.SearchTermHistoryModel>>.value(
                    _i4.dummyValue<_i3.Response<_i6.SearchTermHistoryModel>>(
              this,
              Invocation.method(
                #apiV1ProductSearchHistoryTermsGet,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Response<_i6.SearchTermHistoryModel>>);
}

/// A class which mocks [HydratedStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockHydratedStorage extends _i1.Mock implements _i7.HydratedStorage {
  MockHydratedStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic read(String? key) => super.noSuchMethod(Invocation.method(
        #read,
        [key],
      ));
  @override
  _i5.Future<void> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
```

6.X.X generated version of the file 
```dart
// Mocks generated by Mockito 5.4.2 from annotations
// in mobile_shop/test/src/presentation/features/search_results/bloc/search_result_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chopper/chopper.dart' as _i2;
import 'package:hydrated_bloc/src/hydrated_storage.dart' as _i6;
import 'package:mobile_shop/src/core/bfm/generated/mobile_facade.models.swagger.dart'
    as _i5;
import 'package:mobile_shop/src/core/bfm/generated/mobile_facade.swagger.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChopperClient_0 extends _i1.SmartFake implements _i2.ChopperClient {
  _FakeChopperClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeType_1 extends _i1.SmartFake implements Type {
  _FakeType_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2<BodyType> extends _i1.SmartFake
    implements _i2.Response<BodyType> {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MobileFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockMobileFacade extends _i1.Mock implements _i3.MobileFacade {
  MockMobileFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChopperClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeChopperClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.ChopperClient);
  @override
  set client(_i2.ChopperClient? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Type get definitionType => (super.noSuchMethod(
        Invocation.getter(#definitionType),
        returnValue: _FakeType_1(
          this,
          Invocation.getter(#definitionType),
        ),
      ) as Type);
  @override
  _i4.Future<_i2.Response<_i5.AuthorizationModel>>
      apiV1AuthenticationTokenPost({
    String? authenticationToken,
    String? accountId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #apiV1AuthenticationTokenPost,
              [],
              {
                #authenticationToken: authenticationToken,
                #accountId: accountId,
              },
            ),
            returnValue: _i4.Future<_i2.Response<_i5.AuthorizationModel>>.value(
                _FakeResponse_2<_i5.AuthorizationModel>(
              this,
              Invocation.method(
                #apiV1AuthenticationTokenPost,
                [],
                {
                  #authenticationToken: authenticationToken,
                  #accountId: accountId,
                },
              ),
            )),
          ) as _i4.Future<_i2.Response<_i5.AuthorizationModel>>);
  @override
  _i4.Future<_i2.Response<_i5.CredentialModel>> apiV1AuthenticationRefreshPost(
          {String? refreshToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1AuthenticationRefreshPost,
          [],
          {#refreshToken: refreshToken},
        ),
        returnValue: _i4.Future<_i2.Response<_i5.CredentialModel>>.value(
            _FakeResponse_2<_i5.CredentialModel>(
          this,
          Invocation.method(
            #apiV1AuthenticationRefreshPost,
            [],
            {#refreshToken: refreshToken},
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.CredentialModel>>);
  @override
  _i4.Future<_i2.Response<dynamic>> apiV1HealthReadinessGet() =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1HealthReadinessGet,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_2<dynamic>(
          this,
          Invocation.method(
            #apiV1HealthReadinessGet,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> apiV1HealthLivenessGet() =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1HealthLivenessGet,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_2<dynamic>(
          this,
          Invocation.method(
            #apiV1HealthLivenessGet,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<List<_i5.CategoryModel>>>
      apiV1ProductCategoriesGet() => (super.noSuchMethod(
            Invocation.method(
              #apiV1ProductCategoriesGet,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Response<List<_i5.CategoryModel>>>.value(
                    _FakeResponse_2<List<_i5.CategoryModel>>(
              this,
              Invocation.method(
                #apiV1ProductCategoriesGet,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Response<List<_i5.CategoryModel>>>);
  @override
  _i4.Future<_i2.Response<_i5.SuggestionsModel>>
      apiV1ProductSearchTypeaheadQueryGet({required String? query}) =>
          (super.noSuchMethod(
            Invocation.method(
              #apiV1ProductSearchTypeaheadQueryGet,
              [],
              {#query: query},
            ),
            returnValue: _i4.Future<_i2.Response<_i5.SuggestionsModel>>.value(
                _FakeResponse_2<_i5.SuggestionsModel>(
              this,
              Invocation.method(
                #apiV1ProductSearchTypeaheadQueryGet,
                [],
                {#query: query},
              ),
            )),
          ) as _i4.Future<_i2.Response<_i5.SuggestionsModel>>);
  @override
  _i4.Future<_i2.Response<_i5.SearchModel>> apiV1ProductSearchPost(
          {required _i5.SearchRequestModel? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1ProductSearchPost,
          [],
          {#body: body},
        ),
        returnValue: _i4.Future<_i2.Response<_i5.SearchModel>>.value(
            _FakeResponse_2<_i5.SearchModel>(
          this,
          Invocation.method(
            #apiV1ProductSearchPost,
            [],
            {#body: body},
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.SearchModel>>);
  @override
  _i4.Future<_i2.Response<_i5.SearchTermHistoryModel>>
      apiV1ProductSearchHistoryTermsGet() => (super.noSuchMethod(
            Invocation.method(
              #apiV1ProductSearchHistoryTermsGet,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Response<_i5.SearchTermHistoryModel>>.value(
                    _FakeResponse_2<_i5.SearchTermHistoryModel>(
              this,
              Invocation.method(
                #apiV1ProductSearchHistoryTermsGet,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Response<_i5.SearchTermHistoryModel>>);
}

/// A class which mocks [HydratedStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockHydratedStorage extends _i1.Mock implements _i6.HydratedStorage {
  MockHydratedStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic read(String? key) => super.noSuchMethod(Invocation.method(
        #read,
        [key],
      ));
  @override
  _i4.Future<void> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

```

**Comment by techouse** [comment] 2023-08-11 14:10
This most likely caused by the recently introduced Dart 3.0 class modifiers.

https://github.com/dart-lang/language/issues/3106 has a potential solution to the problem of 2 opposing designs.

**Comment by frederikstonge** [comment] 2023-08-11 14:29
> This most likely caused by the recently introduced [Dart 3.0 class modifiers](https://github.com/lejard-h/chopper/pull/453).
> 
> [dart-lang/language#3106 (comment)](https://github.com/dart-lang/language/issues/3106#issuecomment-1593145359) has a potential solution to the problem of 2 opposing designs.
> 
> @frederikstonge can you provide a bit more detail on what you are trying to mock, i.e. not just the generated mocks but also the tests.

Of course. I'm using the package https://pub.dev/packages/swagger_dart_code_generator to generate a client for my BFF, and we use it in our cubits.

```dart
blocTest<SearchResultsCubit, SearchResultState>(
      'emits [SearchResultStatus.success] when '
      'searchQuery is successful and returns the product list',
      setUp: () => when(mockMobileFacade.apiV1ProductSearchPost(body: searchRequestModel))
          .thenAnswer((_) async => chopper.Response(http.Response('ok', 200), searchModel)),
      build: () => searchResultsCubit,
      act: (SearchResultsCubit cubit) async => await cubit.searchQuery('query'),
      expect: () => [
        isA<SearchResultState>().having((p0) => p0.searchResultStatus, 'description', SearchResultStatus.loading),
        isA<SearchResultState>().having((p0) => p0.searchResultStatus, 'description', SearchResultStatus.success),
      ],
      verify: (_) async {
        verify(mockMobileFacade.apiV1ProductSearchPost(body: searchRequestModel)).called(1);
      },
    );
```

I get the exception above in setUp, in `when()`.

I have read the issue in dart-lang that you quoted, but I'm not sure how to implement the workaround.

**Comment by techouse** [comment] 2023-08-11 14:37
> I have read the issue in dart-lang that you quoted, but I'm not sure how to implement the workaround.

You can't directly. I'll try to make some mock `mixins`, just like the issue suggest, then you can try to mock those rather than `ChopperClient`

**Comment by techouse** [comment] 2023-08-11 19:22
Can you try to use the mixins added in the repo

```yaml
dependency_overrides:
  chopper:
    git:
      url: https://github.com/techouse/chopper.git
      ref: fix/mocks
      path: chopper
```

**Comment by frederikstonge** [comment] 2023-08-12 11:42
> 

My mocks are auto-generated, I don't see this solution as a viable solution with mockito, but maybe with other mocks packages where you implement it yourself. I guess my solution will be th create a real chopper service and use an http.testing MockClient instead. :(

**Comment by techouse** [comment] 2023-08-12 16:24
> Did you need to add sealed and final modifiers to all classes tho?

No.

I've added them in order to get full control over those classes and prevent them from being extended by users in unexpected ways thereby ensuring that we can add and remove code inside `final` classes without any disruptions to users.

> I guess my solution will be th create a real chopper service and use an http.testing MockClient instead.

Probably better to use composition, yes. Mocking the whole `ChopperClient` is seems overkill just to fake-return an HTTP call.

Have you explored [provideDummy](https://pub.dev/documentation/mockito/latest/mockito/provideDummy.html) and/or [provideDummyBuilder](https://pub.dev/documentation/mockito/latest/mockito/provideDummyBuilder.html) by any chance?

**Comment by techouse** [comment] 2023-08-12 21:01
@frederikstonge I've changed the code in my PR repo and added these specific mocks

- `MockChopperClient`
- `MockChopperLogRecord`
- `MockRequest`
- `MockPartValue`
- `MockPartValueFile`
- `MockResponse`

Can you try to reference them directly?

**Comment by frederikstonge** [comment] 2023-08-13 12:01
provideDummy seems to be working fine! I couldn't find it, the documentation is a bit inexistant and it wasn't in there readme.

As for the mocks, I couldn't try them because of the way https://pub.dev/packages/swagger_dart_code_generator works.

Thank you for your help and time, I really appreciate.

**Comment by techouse** [comment] 2023-08-13 20:56
Heh, yea, the Mockito docs are weird.

Cool, closing this issue.

**Closed by techouse** 2023-08-13 20:56 UTC
Labels: bug
