### ISSUE TITLE
token authorization

### ISSUE THREAD

**Issue by sabaya99** [lejard-h/chopper#122] opened 2020-02-09 17:37 UTC
how to pass bearer token authorization in chopper

**Comment by vijaemanlapaz** [comment] 2020-02-14 08:15
same here, how can we pass **Authorization** header on request via **Interceptor**

**Comment by javierjmc** [comment] 2020-02-16 07:29
Just add a request interceptor like this:

```
    ChopperClient(
       ...
        interceptors: [
          (Request request) async {
            await request.headers.putIfAbsent(
                'Authorization',
                () =>
                    'Bearer authToken');
            return request;
          }
        ],
      ));
```

`authToken` can be injected, fetched from shared preference or something like that.

**Comment by vijaemanlapaz** [comment] 2020-02-17 11:09
![Inkedcode_LI](https://user-images.githubusercontent.com/1444097/74648337-6b0bf700-51b8-11ea-8a38-5c87b8c88a6c.jpg)

above is my code
no luck, im getting the following exceptions

![Screenshot_1](https://user-images.githubusercontent.com/1444097/74648613-fe452c80-51b8-11ea-86d3-e70ce7cb9bd8.png)

**Comment by javierjmc** [comment] 2020-02-18 14:03
You need to await the Future from your sharedpreferences, otherwise by the time it answers the interception already finished.

**Comment by vijaemanlapaz** [comment] 2020-02-24 19:36
@javierjmc 
> You need to await the Future from your sharedpreferences, otherwise by the time it answers the interception already finished.

I did await for the sharedpreferences still not working.


**Update:**
Finally got it to work. here's what i ended up doing.


**ApiService.dart**
![ApiService](https://user-images.githubusercontent.com/1444097/75184805-edc81f80-577f-11ea-959b-ded6f465bff9.png)

**HeaderInterceptor.dart**
![HeaderInterceptor](https://user-images.githubusercontent.com/1444097/75184802-e86ad500-577f-11ea-81af-857d99079528.png)

**Comment by JEuler** [comment] 2020-04-10 09:38
I think this can be closed, actually I wrote a little note about this https://medium.com/@JEuler/flutter-http-authorized-requests-801e1d10debf :)

**Comment by stewemetal** [comment] 2020-04-10 21:04
I agree with @JEuler. There are countless articles about the algorithm one can implement with interceptors (mostly using Retrofit and OkHttp interceptors, but Chopper is conceptually the same) to do token authenticated requests and token refreshing.

Basically, the algorithm goes like this:

Add the authentication token to the request (by "Authentication" header, for example) -> try the request -> if it fails use the refresh token to get a new auth token -> 
1) if that succeeds, save the auth token and retry the original request with it
2) if the refresh token is not valid anymore, drop the session (and navigate to the login screen, for example)

Of course, the actual implementation may vary based on how the backend API of your project looks like.

**Comment by JEuler** [comment] 2020-04-16 04:32
Should we close this guys? :)

**Comment by stewemetal** [comment] 2020-04-16 06:21
I believe we should. :)

**Closed by stewemetal** 2020-04-16 06:21 UTC
Labels: enhancement

**Comment by P-B1101** [comment] 2020-07-19 08:21
> I agree with @JEuler. There are countless articles about the algorithm one can implement with interceptors (mostly using Retrofit and OkHttp interceptors on Android, but Chopper is conceptually the same) to do token authenticated requests and token refreshing.
> 
> Basically, the algorithm goes like this:
> 
> Add the authentication token to the request (by "Authorization" header, for example) -> try the request -> if it fails use the refresh token to get a new auth token ->
> 
> 1. if that succeeds, save the auth token and retry the original request with it
> 2. if the refresh token is not valid anymore, drop the session (and navigate to the login screen, for example)
> 
> Of course, the actual implementation may vary based on how the backend API of your project looks like.

how can i retry original request. i actually do this by custom interceptor class. but there is a problem.
the problem is this line of code in base.dart
```
    assert(
      body == res.body,
      'Interceptors should not transform the body of the response'
      'Use Response converter instead',
    );
```
this assert wont let me to return new res.body. the original body is null because of error 401, but the new body is the right one.  and because of "my_body != null" it throw error.
what i do for now is edit base.dart and remove this part of code. (i don't know if the file remain edited or it will reproduce after flutter pub get command).
any better idea?

**Comment by P-B1101** [comment] 2020-07-19 08:23
this is my custom interceptor class.
```
class TokenInterceptor<T> implements RequestInterceptor, ResponseInterceptor {
  static Request _request;
  final ChopperService service;

  TokenInterceptor(this.service);

  @override
  FutureOr<Request> onRequest(Request request) {
    _request = request;
    String token = PrefManager.getToken();
    print(token);
    Map<String, String> mHeader = Map.from(request.headers);
    if (token != null && token.isNotEmpty) {
      mHeader.putIfAbsent("Authorization", () => token);
    }
    Request mRequest = Request(
      request.method,
      request.url,
      request.baseUrl,
      headers: mHeader,
      body: request.body,
      multipart: request.multipart,
      parameters: request.parameters,
      parts: request.parts,
    );
    return mRequest;
  }

  @override
  FutureOr<Response> onResponse(Response<dynamic> response) async {
    if (response.statusCode != 401) return response;
    if (!(await _refreshToken())) return response;
    if (_request == null) return response;
    final request = _request;
    String token = PrefManager.getToken();
    Map<String, String> mHeader = Map.from(request.headers);
    mHeader.remove("Authorization");
    if (token != null && token.isNotEmpty) {
      mHeader.putIfAbsent("Authorization", () => token);
    }
    Request mRequest = Request(
      request.method,
      request.url,
      request.baseUrl,
      headers: mHeader,
      body: request.body,
      multipart: request.multipart,
      parameters: request.parameters,
      parts: request.parts,
    );
    final client = ChopperClient(
      baseUrl: _request.baseUrl,
      services: [service],
      converter: BuiltValueConverter(),
      errorConverter: JsonConverter(),
    );
    Response<T> finalResponse = await client.send<T, T>(mRequest);
    return response.copyWith<T>(base: finalResponse.base,body: finalResponse.body,bodyError: finalResponse.error);
  }

  Future<bool> _refreshToken() async {
    String refreshToken = PrefManager.getRefreshToken();
    UserApiServices api = UserApiServices.createUser<LoginUser>(false);
    ResultModel<LoginUser> resultModel = await _asyncCallApi<LoginUser>(
      api: api.refreshToken(
        refreshToken,
        RestUtils.getGrantTypeRefreshToken(),
        RestUtils.getClientId(),
        RestUtils.getClientSecret(),
      ),
    );
    LoginUser user = resultModel.result;
    if (user == null) return false;
    PrefManager.saveAuthData(user);
    await UserServices(user: user).saveUserInfo();
    return true;
  }

  Future<ResultModel<T>> _asyncCallApi<T>({
    Future<Response<T>> api,
  }) async {
    ResultModel<T> resultModel = ResultModel();
    try {
      Response<T> response = await api;
      resultModel.result = response.body;
      resultModel.status = ResultStatus.OK;
    } catch (error) {
      if (error.runtimeType == IOException)
        resultModel.status = ResultStatus.FAIL;
      else if (error.runtimeType == TimeoutException)
        resultModel.status = ResultStatus.TIME_OUT;
    }
    return resultModel;
  }
}
```
