### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'MyModel'

### ISSUE THREAD

**Issue by bawantha** [lejard-h/chopper#333] opened 2022-03-10 09:05 UTC

**Comment by FabriBertani** [comment] 2022-03-29 02:59
I'm having this issue too

**Comment by JEuler** [comment] 2022-06-24 10:47
Hi! Sorry for delay (DELAY), but please provide more details. It is often related to "wrong" model implementation.

**Comment by techouse** [comment] 2022-08-23 09:28
Duplicate of https://github.com/lejard-h/chopper/issues/330

**Closed** 2022-09-13 15:01 UTC
