### ISSUE TITLE
wrong behavoir when sending list in multipart

### ISSUE THREAD

**Issue by humazed** [lejard-h/chopper#93] opened 2019-09-06 09:33 UTC
shen I use this method:

```dart
  @Post(path: "store/addresses")
  @multipart
  Future<Response<Address>> createAddress(
    @Part("extra[]") List<String> extra,
  );
```

when I call it with:
```dart
createAddress(['ad1', 'ad2']);
```

the sent value is `"[ad1, ad2]"` as one string not as a list
looking at the `request` class it's clear why this happening

`toMultipartRequest` method doesn't handle the case when the part is Iterable
and just convert it to one string.

**Comment by humazed** [comment] 2019-09-06 09:45
here is my hacky solution 
https://github.com/humazed/chopper/blob/a3ca03bb3b56f63ba2aaf1f7c7c0c1a0b36f0795/chopper/lib/src/request.dart#L191

**Comment by humazed** [comment] 2019-09-06 13:48
here is my hacky solution
https://github.com/humazed/chopper/blob/8a2cd739349ebf3f927e53063866afe2ed1860fd/chopper2/lib/src/request.dart#L192

**Comment by lejard-h** [comment] 2019-09-29 11:29
This is actually a duplicate of https://github.com/lejard-h/chopper/issues/61

**Closed** 2019-09-29 11:31 UTC
Labels: duplicate
